name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name : build main branch
    permissions: write-all
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: Build Docker image
#        run: docker build -t daily-canvas

#      - name: Push to GitHub Packages
#        uses: docker/build-push-action@v1
#        with :
#          username: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: univ-smb-m1-isc-2023/DailyCanvas/main
#          tags: latest
